#!/bin/sh

################################################################################
# Configuration variables for image.sh
# These variables are used across different scripts under the image script and
# should be updated according to your system.
################################################################################

INTERFACE=<INTERFACE> # Public IP interface name (e.g. eth1)
IP_ADDRESS1=<IP_ADDRESS1> # Public IP address for the first node (xxx.xx.xxx.xx/xx)
IP_ADDRESS2=<IP_ADDRESS2> # Public IP address for the second node (xxx.xx.xxx.xx/xx)
IP_ADDRESS3=<IP_ADDRESS3> # Public IP address for the third node (xxx.xx.xxx.xx/xx)
NODE1_MAC=<NODE1_MAC> # Public interface MAC address for the first node
NODE2_MAC=<NODE2_MAC> # Public interface MAC address for the second node
NODE3_MAC=<NODE3_MAC> # Public interface MAC address for the third node